extend type Query {
    """
    Returns all allowed tokens for a given chain or chains
    """
    tokenGetTokens(chains: [GqlChain!]!, where: GqlTokenFilter): [GqlToken!]!
    """
    Returns all current prices for allowed tokens for a given chain or chains
    """
    tokenGetCurrentPrices(chains: [GqlChain!]!): [GqlTokenPrice!]!
}

extend type Mutation {
    tokenReloadTokenPrices(chains: [GqlChain!]!): Boolean
    tokenSyncTokenDefinitions: String!
    tokenDeleteTokenType(tokenAddress: String!, type: GqlTokenType!, chain: GqlChain!): String!
    tokenReloadAllTokenTypes(chain: GqlChain!): String!
    tokenReloadErc4626Tokens(chains: [GqlChain!]!): [GqlTokenMutationResult!]!
}

"""
Result of the poolReloadPools mutation
"""
type GqlTokenMutationResult {
    """
    The chain that was reloaded.
    """
    chain: GqlChain!
    """
    Whether it was successful or not.
    """
    success: Boolean!
    """
    The error message
    """
    error: String
}

type GqlTokenPrice {
    address: String!
    chain: GqlChain!
    price: Float!
    updatedAt: Int!
    updatedBy: String
}

"""
Represents a token in the system
"""
type GqlToken {
    """
    The address of the token
    """
    address: String!
    """
    The name of the token
    """
    name: String!
    """
    The description of the token
    """
    description: String
    """
    The symbol of the token
    """
    symbol: String!
    """
    The number of decimal places for the token
    """
    decimals: Int!
    """
    The chain ID of the token
    """
    chainId: Int!
    """
    The website URL of the token
    """
    websiteUrl: String
    """
    The Discord URL of the token
    """
    discordUrl: String
    """
    The Telegram URL of the token
    """
    telegramUrl: String
    """
    The Twitter username of the token
    """
    twitterUsername: String
    """
    The logo URI of the token
    """
    logoURI: String
    """
    The coingecko ID for this token, if present
    """
    coingeckoId: String
    """
    The priority of the token, can be used for sorting.
    """
    priority: Int!
    """
    Indicates if the token is tradable
    """
    tradable: Boolean!
    """
    The chain of the token
    """
    chain: GqlChain!
    """
    The rate provider data for the token
    """
    priceRateProviderData: GqlPriceRateProviderData
    """
    Whether the token is considered an ERC4626 token.
    """
    isErc4626: Boolean!
    """
    The ERC4626 underlying token address, if applicable.
    """
    underlyingTokenAddress: String
    """
    If it is an ERC4626 token, this defines whether we allow it to use the buffer for pool operations.
    """
    isBufferAllowed: Boolean!
    """
    The ERC4626 review data for the token
    """
    erc4626ReviewData: Erc4626ReviewData
    types: [GqlTokenType!]
    """
    If it is an ERC4626 token, this  defines how much can be deposited into the ERC4626 vault.
    """
    maxDeposit: String
}

"""
Represents the data of a price rate provider
"""
type GqlPriceRateProviderData {
    """
    The address of the price rate provider
    """
    address: String!
    """
    Indicates if the price rate provider has been reviewed
    """
    reviewed: Boolean!
    """
    The name of the price rate provider
    """
    name: String
    """
    A summary of the price rate provider, usually just says safe or unsafe
    """
    summary: String
    """
    The filename of the review of the price rate provider
    """
    reviewFile: String
    """
    Warnings associated with the price rate provider
    """
    warnings: [String!]
    """
    The factory used to create the price rate provider, if applicable
    """
    factory: String
    """
    Upgradeable components of the price rate provider
    """
    upgradeableComponents: [GqlPriceRateProviderUpgradeableComponent]
}

"""
Represents an upgradeable component of a price rate provider
"""
type GqlPriceRateProviderUpgradeableComponent {
    """
    The entry point / proxy of the upgradeable component
    """
    entryPoint: String!
    """
    Indicates if the implementation of the component has been reviewed
    """
    implementationReviewed: String!
}

enum GqlTokenType {
    BLOCKED_V2
    BLOCKED_V3
    BPT
    PHANTOM_BPT
    ERC4626
}
"""
Provide filters for tokens
"""
input GqlTokenFilter {
    """
    Only return tokens with these addresses
    """
    tokensIn: [String!]
    """
    Filter by token type
    """
    typeIn: [GqlTokenType!]
}

"""
The review data for the ERC4626 token
"""
type Erc4626ReviewData {
    """
    A summary of the ERC4626 review, usually just says safe or unsafe
    """
    summary: String!
    """
    The filename of the review of the ERC4626
    """
    reviewFile: String!
    """
    Warnings associated with the ERC4626
    """
    warnings: [String!]!
    """
    If it is an ERC4626 token, this defines whether we can use wrap/unwrap through the buffer in swap paths for this token.
    """
    canUseBufferForSwaps: Boolean
    """
    If it is an ERC4626 token, this defines whether we allow underlying tokens to be used for add/remove operations.
    """
    useUnderlyingForAddRemove: Boolean
    """
    If it is an ERC4626 token, this defines whether we allow the wrapped tokens to be used for add/remove operations.
    """
    useWrappedForAddRemove: Boolean
}
