query BalancerPoolShares(
    $skip: Int
    $first: Int
    $orderBy: PoolShare_orderBy
    $orderDirection: OrderDirection
    $where: PoolShare_filter
    $block: Block_height
) {
    poolShares(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...BalancerPoolShare
    }
}

fragment BalancerPoolShare on PoolShare {
    id
    balance
    poolId {
        id
    }
}

fragment BalancerPool on Pool {
    id
    address
    poolType
    poolTypeVersion
    symbol
    name
    swapFee
    totalShares
    createTime
    swapEnabled
    tokensList
    factory
    owner
    amp
    alpha
    beta
    sqrtAlpha
    sqrtBeta
    root3Alpha
    c
    s
    lambda
    tauAlphaX
    tauAlphaY
    tauBetaX
    tauBetaY
    u
    v
    w
    z
    dSq

    priceRateProviders {
        address
        token {
            address
        }
    }

    tokens {
        ...BalancerPoolToken
    }
}

fragment BalancerPoolToken on PoolToken {
    id
    symbol
    name
    decimals
    address
    balance
    weight
    priceRate
    isExemptFromYieldProtocolFee
    index
}

query BalancerPools(
    $skip: Int
    $first: Int
    $orderBy: Pool_orderBy
    $orderDirection: OrderDirection
    $where: Pool_filter
    $block: Block_height
) {
    pools(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...BalancerPool
    }
}

query BalancerJoinExits(
    $skip: Int
    $first: Int
    $orderBy: JoinExit_orderBy
    $orderDirection: OrderDirection
    $where: JoinExit_filter
    $block: Block_height
) {
    joinExits(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...BalancerJoinExit
    }
}

fragment BalancerJoinExit on JoinExit {
    amounts
    id
    sender
    block
    timestamp
    tx
    type
    pool {
        id
        tokensList
    }
}

query BalancerSwaps(
    $skip: Int
    $first: Int
    $orderBy: Swap_orderBy
    $orderDirection: OrderDirection
    $where: Swap_filter
    $block: Block_height
) {
    swaps(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...BalancerSwap
    }
}

fragment BalancerSwap on Swap {
    id
    tokenIn
    tokenOut
    tokenAmountIn
    tokenAmountOut
    poolId {
        id
        swapFee
    }
    userAddress
    timestamp
    tx
    block
}

query BalancerGetMeta {
    meta: _meta {
        block {
            number
        }
    }
}
