fragment VaultPool on Pool {
    id
    isPaused
    isInRecoveryMode
    swapFee
    address
    name
    symbol
    totalShares
    pauseManager
    swapFeeManager
    poolCreator
    blockTimestamp
    tokens {
        address
        index
        name
        symbol
        decimals
        balance
        paysYieldFees
        scalingFactor
    }
    rateProviders {
        address
    }
    hookConfig {
        hook {
            address
        }
        enableHookAdjustedAmounts
        shouldCallAfterSwap
        shouldCallBeforeSwap
        shouldCallAfterInitialize
        shouldCallBeforeInitialize
        shouldCallAfterAddLiquidity
        shouldCallBeforeAddLiquidity
        shouldCallAfterRemoveLiquidity
        shouldCallBeforeRemoveLiquidity
        shouldCallComputeDynamicSwapFee
    }
    liquidityManagement {
        disableUnbalancedLiquidity
        enableAddLiquidityCustom
        enableDonation
        enableRemoveLiquidityCustom
    }
}

query Pools(
    $skip: Int
    $first: Int
    $orderBy: Pool_orderBy
    $orderDirection: OrderDirection
    $where: Pool_filter
    $block: Block_height
) {
    pools(
        skip: $skip
        first: $first
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
        block: $block
    ) {
        ...VaultPool
    }
}
