query GaugeLiquidityGauges(
    $first: Int = 1000
    $orderBy: LiquidityGauge_orderBy
    $orderDirection: OrderDirection
    $skip: Int = 0
    $where: LiquidityGauge_filter
) {
    liquidityGauges(skip: $skip, first: $first, orderBy: $orderBy, orderDirection: $orderDirection, where: $where) {
        ...Gauge
    }
}

fragment Gauge on LiquidityGauge {
    id
    poolId
    poolAddress
    tokens {
        id
        decimals
    }
    isPreferentialGauge
    isKilled
}

query GaugeShares(
    $block: Block_height
    $first: Int = 100
    $orderBy: GaugeShare_orderBy
    $orderDirection: OrderDirection
    $skip: Int = 0
    $where: GaugeShare_filter
) {
    gaugeShares(
        block: $block
        first: $first
        skip: $skip
        orderBy: $orderBy
        orderDirection: $orderDirection
        where: $where
    ) {
        ...GaugeShare
    }
}

fragment GaugeShare on GaugeShare {
    id
    balance
    gauge {
        id
        poolAddress
    }
    user {
        id
    }
}

query GaugeGetMeta {
    meta: _meta {
        block {
            number
        }
    }
}
